export const quotes: string[] = [
  `May the Force be with you.`,
  `I'm the king of the world!`,
  `Elementary, my dear Watson.`,
  `It's alive! It's alive!`,
  `My mama always said life was like a box of chocolates. You never know what you're gonna get.`,
  `You're gonna need a bigger boat.`,
  `Life is a banquet, and most poor suckers are starving to death!`,
  `The stuff that dreams are made of.`,
  `Magic Mirror on the wall, who is the fairest one of all?`,
  `Keep your friends close, but your enemies closer.`,
  `Today, I consider myself the luckiest man on the face of the earth.`,
  `You is kind. You is smart. You is important.`,
  `What we've got here is failure to communicate.`,
  `I'm walking here! I'm walking here!`,
  `I'll have what she's having.`,
  `All right, Mr. DeMille, I'm ready for my close-up.`,
  `Fasten your seatbelts. It's going to be a bumpy night.`,
  `They may take our lives, but they'll never take our freedom!`,
  `Toto, I've a feeling we're not in Kansas anymore.`,
  `I love the smell of napalm in the morning.`,
  `Fasten your seatbelts. It's going to be a bumpy night.`,
  `All right, Mr. DeMille, I'm ready for my close-up.`,
  `I'm as mad as hell, and I'm not going to take this anymore!`,
  `A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.`,
  `Why don't you come up sometime and see me?`,
  `After all, tomorrow is another day!`,
  `You know how to whistle, don't you, Steve? You just put your lips together and blow.`,
  `Today, I consider myself the luckiest man on the face of the Earth.`,
  `Mama always said life was like a box of chocolates. You never know what you're gonna get.`,
  `Oh, Jerry, don't let's ask for the moon. We have the stars.`,
]
